import {
  Apple,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Atom,
  Award,
  Bell,
  Bike,
  Book,
  BookOpen,
  Bookmark,
  Brain,
  Brush,
  Calculator,
  Calendar,
  Camera,
  Car,
  ChartBar,
  ChartLine,
  ChartPie,
  Check,
  CircleCheck,
  CircleQuestionMark,
  CircleX,
  Clock,
  Cloud,
  Code,
  Coffee,
  Cpu,
  Crown,
  Database,
  Divide,
  Dna,
  Droplet,
  Equal,
  Eye,
  Flag,
  Flame,
  FlaskConical,
  Footprints,
  Gift,
  Globe,
  GraduationCap,
  Hand,
  Hash,
  Heart,
  Hourglass,
  House,
  Infinity as InfinityIcon,
  Info,
  Key,
  Leaf,
  Lightbulb,
  Lock,
  Mail,
  Map,
  MapPin,
  Megaphone,
  MessageCircle,
  Mic,
  Microscope,
  Minus,
  Moon,
  Mountain,
  Music,
  Palette,
  Paperclip,
  Pencil,
  Percent,
  Phone,
  Pi,
  Pin,
  Pizza,
  Plane,
  Plus,
  Presentation,
  Puzzle,
  Rocket,
  Ruler,
  Scissors,
  Search,
  Settings,
  Shapes,
  Ship,
  Sigma,
  Sparkles,
  Star,
  Sun,
  Target,
  ThumbsDown,
  ThumbsUp,
  Timer,
  TreePine,
  TriangleAlert,
  Trophy,
  User,
  Users,
  Video,
  X,
  Zap,
  type LucideIcon,
} from "lucide-react";

export interface BoardIcon {
  name: string;
  // Extra words the search box matches on.
  keywords: string;
  Icon: LucideIcon;
}

// The built-in icon set of the media tool. Placed on the board as SVG in the
// current pen color, so they stay crisp at any size.
export const BOARD_ICONS: BoardIcon[] = [
  { name: "Star", keywords: "favorite rating", Icon: Star },
  { name: "Heart", keywords: "love like", Icon: Heart },
  { name: "Check", keywords: "tick done correct yes", Icon: Check },
  { name: "Cross", keywords: "x wrong no close", Icon: X },
  { name: "Correct", keywords: "check circle done", Icon: CircleCheck },
  { name: "Incorrect", keywords: "x circle wrong", Icon: CircleX },
  { name: "Question", keywords: "help ask", Icon: CircleQuestionMark },
  { name: "Info", keywords: "information note", Icon: Info },
  { name: "Warning", keywords: "alert caution", Icon: TriangleAlert },
  { name: "Idea", keywords: "lightbulb think", Icon: Lightbulb },
  { name: "Arrow right", keywords: "next direction", Icon: ArrowRight },
  { name: "Arrow left", keywords: "back direction", Icon: ArrowLeft },
  { name: "Arrow up", keywords: "direction increase", Icon: ArrowUp },
  { name: "Arrow down", keywords: "direction decrease", Icon: ArrowDown },
  { name: "Plus", keywords: "add math", Icon: Plus },
  { name: "Minus", keywords: "subtract math", Icon: Minus },
  { name: "Divide", keywords: "math division", Icon: Divide },
  { name: "Equals", keywords: "math equal", Icon: Equal },
  { name: "Percent", keywords: "math percentage", Icon: Percent },
  { name: "Pi", keywords: "math", Icon: Pi },
  { name: "Sigma", keywords: "sum math", Icon: Sigma },
  { name: "Infinity", keywords: "math forever", Icon: InfinityIcon },
  { name: "Hash", keywords: "number", Icon: Hash },
  { name: "Calculator", keywords: "math", Icon: Calculator },
  { name: "Ruler", keywords: "measure geometry", Icon: Ruler },
  { name: "Shapes", keywords: "geometry", Icon: Shapes },
  { name: "Bar chart", keywords: "graph data statistics", Icon: ChartBar },
  { name: "Line chart", keywords: "graph data trend", Icon: ChartLine },
  { name: "Pie chart", keywords: "graph data share", Icon: ChartPie },
  { name: "Book", keywords: "read study", Icon: Book },
  { name: "Open book", keywords: "read study", Icon: BookOpen },
  { name: "Graduation", keywords: "school student", Icon: GraduationCap },
  { name: "Pencil", keywords: "write edit", Icon: Pencil },
  { name: "Brush", keywords: "paint art", Icon: Brush },
  { name: "Palette", keywords: "art color", Icon: Palette },
  { name: "Scissors", keywords: "cut craft", Icon: Scissors },
  { name: "Paperclip", keywords: "attach", Icon: Paperclip },
  { name: "Pin", keywords: "note attach", Icon: Pin },
  { name: "Bookmark", keywords: "save", Icon: Bookmark },
  { name: "Flag", keywords: "goal milestone", Icon: Flag },
  { name: "Target", keywords: "goal aim", Icon: Target },
  { name: "Trophy", keywords: "win award", Icon: Trophy },
  { name: "Award", keywords: "badge medal", Icon: Award },
  { name: "Crown", keywords: "king winner", Icon: Crown },
  { name: "Gift", keywords: "present reward", Icon: Gift },
  { name: "Sparkles", keywords: "magic new", Icon: Sparkles },
  { name: "Thumbs up", keywords: "like good yes", Icon: ThumbsUp },
  { name: "Thumbs down", keywords: "dislike bad no", Icon: ThumbsDown },
  { name: "Hand", keywords: "raise wave", Icon: Hand },
  { name: "Eye", keywords: "look see", Icon: Eye },
  { name: "Brain", keywords: "think mind", Icon: Brain },
  { name: "Puzzle", keywords: "problem solve", Icon: Puzzle },
  { name: "Person", keywords: "user student", Icon: User },
  { name: "People", keywords: "users group team", Icon: Users },
  { name: "Presentation", keywords: "teach board", Icon: Presentation },
  { name: "Megaphone", keywords: "announce", Icon: Megaphone },
  { name: "Message", keywords: "chat speech", Icon: MessageCircle },
  { name: "Mail", keywords: "email letter", Icon: Mail },
  { name: "Phone", keywords: "call", Icon: Phone },
  { name: "Bell", keywords: "notification", Icon: Bell },
  { name: "Clock", keywords: "time", Icon: Clock },
  { name: "Timer", keywords: "time stopwatch", Icon: Timer },
  { name: "Hourglass", keywords: "time wait", Icon: Hourglass },
  { name: "Calendar", keywords: "date schedule", Icon: Calendar },
  { name: "Home", keywords: "house", Icon: House },
  { name: "Globe", keywords: "world earth", Icon: Globe },
  { name: "Map", keywords: "geography", Icon: Map },
  { name: "Location", keywords: "map pin place", Icon: MapPin },
  { name: "Mountain", keywords: "nature geography", Icon: Mountain },
  { name: "Tree", keywords: "nature pine", Icon: TreePine },
  { name: "Leaf", keywords: "nature plant", Icon: Leaf },
  { name: "Sun", keywords: "weather day", Icon: Sun },
  { name: "Moon", keywords: "night", Icon: Moon },
  { name: "Cloud", keywords: "weather", Icon: Cloud },
  { name: "Water", keywords: "droplet rain", Icon: Droplet },
  { name: "Fire", keywords: "flame hot", Icon: Flame },
  { name: "Energy", keywords: "zap lightning electricity", Icon: Zap },
  { name: "Atom", keywords: "science physics", Icon: Atom },
  { name: "Flask", keywords: "science chemistry lab", Icon: FlaskConical },
  { name: "Microscope", keywords: "science biology", Icon: Microscope },
  { name: "DNA", keywords: "science biology", Icon: Dna },
  { name: "Rocket", keywords: "space launch", Icon: Rocket },
  { name: "Code", keywords: "programming computer", Icon: Code },
  { name: "Chip", keywords: "cpu computer", Icon: Cpu },
  { name: "Database", keywords: "data storage", Icon: Database },
  { name: "Settings", keywords: "gear", Icon: Settings },
  { name: "Search", keywords: "find magnify", Icon: Search },
  { name: "Lock", keywords: "secure", Icon: Lock },
  { name: "Key", keywords: "unlock", Icon: Key },
  { name: "Music", keywords: "note song", Icon: Music },
  { name: "Microphone", keywords: "mic audio", Icon: Mic },
  { name: "Camera", keywords: "photo", Icon: Camera },
  { name: "Video", keywords: "film", Icon: Video },
  { name: "Car", keywords: "transport", Icon: Car },
  { name: "Bike", keywords: "bicycle transport", Icon: Bike },
  { name: "Plane", keywords: "flight travel", Icon: Plane },
  { name: "Ship", keywords: "boat travel", Icon: Ship },
  { name: "Footprints", keywords: "walk steps", Icon: Footprints },
  { name: "Apple", keywords: "fruit food teacher", Icon: Apple },
  { name: "Pizza", keywords: "food fraction", Icon: Pizza },
  { name: "Coffee", keywords: "drink break", Icon: Coffee },
];
